name: Scheduled build
on:
  schedule:
    - cron: '0 7 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger our build webhook on Netlify
        run: curl -s -X POST "https://api.vercel.com/v1/integrations/deploy/${TOKEN}"
        env:
          TOKEN: ${{ secrets.VERCEL_CRON_BUILD_HOOK }}
