name: Scheduled build
on:
  schedule:
    - cron: '0 8 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger our build webhook on Vercel
        run: curl -s -X POST ${{ secrets.VERCEL_CRON_BUILD_HOOK }}
